# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Traj_Plan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Traj_Plan.proto',
  package='Traj_Plan',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fTraj_Plan.proto\x12\tTraj_Plan\"\xa4\x01\n\nTrajectory\x12\x0c\n\x04\x43ode\x18\x01 \x01(\t\x12\x33\n\nRoadPoints\x18\x02 \x03(\x0b\x32\x1f.Traj_Plan.Trajectory.RoadPoint\x1aS\n\tRoadPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01v\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\x12\x0b\n\x03yaw\x18\x05 \x01(\x02\x12\r\n\x05kappa\x18\x06 \x01(\x02\"\x13\n\x03Log\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2@\n\tTraj_Plan\x12\x33\n\x08TrajPlan\x12\x15.Traj_Plan.Trajectory\x1a\x0e.Traj_Plan.Log\"\x00\x62\x06proto3'
)




_TRAJECTORY_ROADPOINT = _descriptor.Descriptor(
  name='RoadPoint',
  full_name='Traj_Plan.Trajectory.RoadPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Traj_Plan.Trajectory.RoadPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Traj_Plan.Trajectory.RoadPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v', full_name='Traj_Plan.Trajectory.RoadPoint.v', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='a', full_name='Traj_Plan.Trajectory.RoadPoint.a', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='Traj_Plan.Trajectory.RoadPoint.yaw', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kappa', full_name='Traj_Plan.Trajectory.RoadPoint.kappa', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=195,
)

_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='Traj_Plan.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='Traj_Plan.Trajectory.Code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoadPoints', full_name='Traj_Plan.Trajectory.RoadPoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TRAJECTORY_ROADPOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=195,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='Traj_Plan.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Traj_Plan.Log.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=216,
)

_TRAJECTORY_ROADPOINT.containing_type = _TRAJECTORY
_TRAJECTORY.fields_by_name['RoadPoints'].message_type = _TRAJECTORY_ROADPOINT
DESCRIPTOR.message_types_by_name['Trajectory'] = _TRAJECTORY
DESCRIPTOR.message_types_by_name['Log'] = _LOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), {

  'RoadPoint' : _reflection.GeneratedProtocolMessageType('RoadPoint', (_message.Message,), {
    'DESCRIPTOR' : _TRAJECTORY_ROADPOINT,
    '__module__' : 'Traj_Plan_pb2'
    # @@protoc_insertion_point(class_scope:Traj_Plan.Trajectory.RoadPoint)
    })
  ,
  'DESCRIPTOR' : _TRAJECTORY,
  '__module__' : 'Traj_Plan_pb2'
  # @@protoc_insertion_point(class_scope:Traj_Plan.Trajectory)
  })
_sym_db.RegisterMessage(Trajectory)
_sym_db.RegisterMessage(Trajectory.RoadPoint)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'Traj_Plan_pb2'
  # @@protoc_insertion_point(class_scope:Traj_Plan.Log)
  })
_sym_db.RegisterMessage(Log)



_TRAJ_PLAN = _descriptor.ServiceDescriptor(
  name='Traj_Plan',
  full_name='Traj_Plan.Traj_Plan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=218,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrajPlan',
    full_name='Traj_Plan.Traj_Plan.TrajPlan',
    index=0,
    containing_service=None,
    input_type=_TRAJECTORY,
    output_type=_LOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAJ_PLAN)

DESCRIPTOR.services_by_name['Traj_Plan'] = _TRAJ_PLAN

# @@protoc_insertion_point(module_scope)
