# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Traj_Plan_pb2 as Traj__Plan__pb2


class Traj_PlanStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrajPlan = channel.unary_unary(
                '/Traj_Plan.Traj_Plan/TrajPlan',
                request_serializer=Traj__Plan__pb2.Trajectory.SerializeToString,
                response_deserializer=Traj__Plan__pb2.Log.FromString,
                )


class Traj_PlanServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrajPlan(self, request, context):
        """轨迹规划 协同控制模块调用 数据收发模块转发到智能体
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Traj_PlanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrajPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.TrajPlan,
                    request_deserializer=Traj__Plan__pb2.Trajectory.FromString,
                    response_serializer=Traj__Plan__pb2.Log.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Traj_Plan.Traj_Plan', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Traj_Plan(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrajPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Traj_Plan.Traj_Plan/TrajPlan',
            Traj__Plan__pb2.Trajectory.SerializeToString,
            Traj__Plan__pb2.Log.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
